name: 

on:
  # 1.2
  # push:
  #   branches:
  #     - dev

  # 1.3
  # push:
  #   branches:
  #     - '!staging'

  # 1.4
  # push:
  #   branches:
  #     - 'feat/**'

  # 1.5
  # push:
  #   paths:
  #     - '**.ts'

  # 1.6
  # push:
  #   paths:
  #     - node-app

  # 2.1
  # pull_request:
  #   types:
  #     - opened

  # 2.2
  # pull_request:
  #   types:
  #     - closed

  # 3.1
  # schedule:
  #   - cron: '*/5 * * * *'

  # 3.2
  # schedule:
  #   - cron: '0 0/3 * * *'
  #   - cron: '30 1/3 * * *'

  # 3.3
  # schedule:
  #   - cron: '0 3 * * thu'

  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@4

  deploy:
    runs-on: ubuntu-latest
    steps:
      uses: action/checkout/@4
      if: github.event_name == 'push'
